import { auth } from "@/auth";
import DictionaryProvider from "@/context/dictionary-context";
import { getDictionary } from "@/lib/dictionaries";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const dictionary = await getDictionary("en");
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider
          // refetchInterval={1}
          session={session}
        >
          <DictionaryProvider dictionary={dictionary}>
            {children}
          </DictionaryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
