import { auth } from "@/auth";
import Footer from "@/components/footer";
import Header from "@/components/header";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
};

export default async function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider
      // refetchInterval={1}
      session={session}
    >
      <Header isAuthenticated={session?.user?.userId != null} />
      <main className="min-h-screen flex-grow">{children}</main>
      <Footer />
    </SessionProvider>
  );
}
