import { auth } from "@/auth";
import Footer from "@/components/footer";
import Header from "@/components/header";
import DictionaryProvider from "@/context/dictionary-context";
import { getDictionary } from "@/lib/dictionaries";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
};

export default async function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const dictionary = await getDictionary("en");
  return (
    <SessionProvider
      // refetchInterval={1}
      session={session}
    >
      <DictionaryProvider dictionary={dictionary}>
        <Header isAuthenticated={session?.user?.userId != null} />
        <main className="min-h-screen flex-grow">{children}</main>
        <Footer />
      </DictionaryProvider>
    </SessionProvider>
  );
}
