import { getCategories } from "@/actions/categories/categories";
import { auth } from "@/auth";
import Footer from "@/components/footer";
import Header from "@/components/header";
import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Amaze hub",
  description: "Generated by create next app",
};

export default async function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const categories = await getCategories();
  return (
    <>
      <Header
        // isAuthenticated={!!session?.user?.userId}
        user={session?.user}
        categories={categories?.data ?? []}
      />
      <div className="min-h-screen flex-grow">{children}</div>
      <Footer />
    </>
  );
}
